Feature/tests
ConsenSys-archive/drizzle-legacy pull request #165
Opened 2019-01-14 21:13 UTC by cds-amal

Built on @DiscRiskandBisque's testing work.
It should merge automatically after we zap `package-lock.json` on master

N.B. I removed web3Saga's `callSendTx` and `createTxChannel`. Please do a manual integration test to make sure all remains copacetic.

2019-01-14 21:35 UTC, adrianmcli requested changes
This is quite a large PR and going forward, we really should have much smaller incremental PRs. There's also a lot of mocking going on here (which makes me feel extremely un-easy). The maintenance burden for this is going to be non-trivial. Not exactly sure how to deal with that in the context of this PR though.

2019-01-14 21:35 UTC, adrianmcli commented on .eslintrc
> +  "extends": ["standard", "plugin:jest/recommended"],
Are all these specific rules necessary when we are extending the recommended jest config?

2019-01-14 21:35 UTC, adrianmcli commented on .babelrc
> +    "babel-plugin-syntax-async-functions"
How come this was changed for the tests? Isn't Babel only related to the production build?

2019-01-14 21:35 UTC, adrianmcli commented on package.json
> +    "ganache-core": "^2.3.3",
We need both `ganache-cli` and `ganache-core`? I am under the impression that we only really need one.

2019-01-14 21:35 UTC, adrianmcli commented on package.json
> +    "chai": "^4.2.0",
Why is Chai necessary if we are using Jest?

2019-01-14 21:35 UTC, adrianmcli commented on package.json
> +    "mocha": "^5.2.0",
Why is Mocha necessary if we are using Jest?

2019-01-14 21:35 UTC, adrianmcli commented on src/web3/web3Saga.js
> +export function* initializeWeb3({ options }) {
Did you run `npm run format` before submitting the PR?

2019-01-14 21:35 UTC, adrianmcli commented on src/web3/web3Reducer.js
> +  if (action.type === Action.WEB3_INITIALIZING) {
Might be worthwhile to de-structure from `Action`. Same for the rest of this file.

2019-01-14 21:35 UTC, adrianmcli commented on src/web3/web3Saga.js
> +      yield put({ type: Action.WEB3_INITIALIZED })
Consider de-structuring from `Action`. Same for rest of the file.

2019-01-14 21:35 UTC, adrianmcli commented on test/accountBalances.test.js
> +  ;[mockedStore, dispatchedActions] = mockDrizzleStore(state)
This semi-colon here is weird, might be able to get rid of it with the formatter (not sure if it's enabled for test folder though)?

2019-01-14 21:35 UTC, adrianmcli commented on test/blocks.test.js
> +  ;[mockedStore] = mockDrizzleStore()
Another strange semi-colon.

2019-01-14 21:35 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Another strange leading semi-colon.

2019-01-14 21:35 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Another strange leading semi-colon.

2019-01-14 21:35 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Another strange leading semi-colon.

2019-01-14 21:35 UTC, adrianmcli commented on .gitignore
> +package-lock.json
Why is `package-lock.json` ignored?

2019-01-14 21:48 UTC, honestbonsai requested changes

2019-01-14 21:48 UTC, honestbonsai commented on .tern-project
> +{
Is this IDE specific? If so, ignore it.

2019-01-14 21:48 UTC, honestbonsai commented on .gitignore
> +package-lock.json
Shouldn't ignore `package-lock.json`, we should check this into git. npm's way of ensuring deterministic installs I believe. Like yarn's lockfile.

2019-01-14 21:48 UTC, honestbonsai commented on CONTRIBUTING.md
> +No tests found related to files changed since last commit.
Not sure if we need this here. The instructions that jest gives in the console seem straightforward to me.

However, I don't think we should set jest's watch as the default for `npm test`. I'd suggest using just the basic single run jest as the default. Use `npm test:watch` or something to activate jest's watch mode.

2019-01-14 21:48 UTC, honestbonsai commented on jest.config.js
> +module.exports = {
Should only keep the active options in the jest config. It's hard to see what is active in this file with all the commented out code.

2019-01-14 21:48 UTC, honestbonsai commented on package.json
> +    "test": "jest --notify --watch",
Mentioned above that we should probably just use the single run jest for `test`.

And jest's watch mode for `test:watch`

2019-01-14 21:48 UTC, honestbonsai commented on src/web3/web3Saga.js
> +export function* getNetworkId({ web3 }) {
Do a run of `npm run format` to get rid of these editor-made formatting things.

Though we should really just do this through `husky` and `lint-staged` (but that's for another PR).

2019-01-14 21:48 UTC, honestbonsai commented on src/web3/web3Saga.js
> -  yield takeEvery('SEND_WEB3_TX', callSendTx)
Hmm not sure where this went? Looks like it got removed, but shouldn't it have been moved to another place? What was the reason for it's removal?

2019-01-14 21:58 UTC, honestbonsai requested changes

2019-01-14 21:58 UTC, honestbonsai commented on test/contracts/create.test.js
> +import { /* addContract, */
Remove this if you aren't using it

2019-01-14 21:58 UTC, honestbonsai commented on test/contracts/create.test.js
> +    ;[mockedStore] = mockDrizzleStore({ web3: { networkId: global.defaultNetworkId }, accounts })
Not sure what this semicolon is here for.

2019-01-14 21:58 UTC, honestbonsai commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Another semicolon

2019-01-14 21:58 UTC, honestbonsai commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Another semicolon

2019-01-14 21:58 UTC, honestbonsai commented on test/web3.test.js
> +      // console.log('mEnable', mEnable)
Remove this unused code

2019-01-14 21:58 UTC, honestbonsai commented on test/web3.test.js
> +      // mock can force an exception
Remove this unused code

2019-01-14 22:09 UTC, honestbonsai requested changes

2019-01-14 22:09 UTC, honestbonsai commented on test/accountBalances.test.js
> +  expect(dispatchedActions[0].accountBalance).toEqual(expectedBalance)
Also, I see a lot of tests for actions, but are there any tests to make sure the values flow down to the reducer properly?

2019-01-14 22:11 UTC, cds-amal commented on .eslintrc
> +  "extends": ["standard", "plugin:jest/recommended"],
Good catch! the following are redundant.

-    "jest/no-disabled-tests": "warn",
-    "jest/no-focused-tests": "error",
-    "jest/no-identical-title": "error",
-    "jest/valid-expect": "error"

2019-01-14 22:13 UTC, cds-amal commented on package.json
> +    "ganache-core": "^2.3.3",
Only one is necessary -- removing -cli

2019-01-14 22:14 UTC, cds-amal commented on package.json
> +    "chai": "^4.2.0",
I can't think of a good reason :)

2019-01-14 22:15 UTC, cds-amal commented on package.json
> +    "mocha": "^5.2.0",
I can't think of a good reason, removing it :)

2019-01-14 22:25 UTC, cds-amal commented on src/web3/web3Saga.js
> +export function* initializeWeb3({ options }) {
No, I did know about that. I'll update it to take the tests folder and re sub after I address the other non-formatting issues.

2019-01-14 22:27 UTC, cds-amal commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
It's an artifact of prettier (and my settings?). Without it `prettier` would interpret the snippet as: ```
global.window = {}[(mockedStore, dispatchedActions)] = mockDrizzleStore()
```

an updated `npm run format` should normalize it for the PR.

2019-01-14 22:29 UTC, cds-amal commented on .tern-project
> +{
It's a code analyzer/navigator available for most editors.

2019-01-14 23:02 UTC, cds-amal commented on src/web3/web3Reducer.js
> +  if (action.type === Action.WEB3_INITIALIZING) {
I had the same thought, but think it it's better to be explicit as I want to eventually replace all the magic strings with constants. In this case I prefer this naming convention. The actions can be destructured after wards.

2019-01-15 01:29 UTC, adrianmcli commented on CONTRIBUTING.md
> +No tests found related to files changed since last commit.
Agreed, that would be the standard way of doing things, for CI purposes.

2019-01-15 01:31 UTC, adrianmcli commented on src/web3/web3Saga.js
> -  yield takeEvery('SEND_WEB3_TX', callSendTx)
^ Changed "it's" to "its".

2019-01-15 01:35 UTC, adrianmcli commented on .eslintrc
> +  "extends": ["standard", "plugin:jest/recommended"],
Why do we need the rest of the rules? I'm not convinced we should be adding config unless there are existing patterns which are currently causing bugs.

2019-01-15 16:14 UTC, adrianmcli requested changes
A few more change requests relating to style and naming.

2019-01-15 16:14 UTC, adrianmcli commented on test/web3.test.js
> +    let mEnable
I don't think this variable is necessary, `mEnable` is not used anywhere in the rest of the file.

2019-01-15 16:14 UTC, adrianmcli commented on test/web3.test.js
> +      mEnable = jest.fn((...args) => `hi ${args[0]}`)
I believe you can just assign this directly to `global.provider.enable`.

2019-01-15 16:14 UTC, adrianmcli commented on test/utils/helpers.js
> +  const web3Provider = new Web3(global.provider)
Naming issue: this is a `Web3` instance as opposed to a `Provider` instance. Below, you use it with the `web3.eth.Contract` constructor and `web3.eth.getAccounts` method.

2019-01-15 16:14 UTC, adrianmcli commented on test/utils/helpers.js
> +const mockWeb3 = () => new Web3(global.provider)
Naming issue: `mockWeb3` and `mockWeb3Assets` don't seem to be function mocks at all. They look like they are the real thing. Might be better to just drop the `mock` part of their names, and replace it with `create` or `get` instead.

2019-01-15 16:14 UTC, adrianmcli commented on test/web3.test.js
> +let mockedStore, dispatchedActions, web3Options, resolvedWeb3
Do these really need to be in the outer scope like this? It looks like a lot of these keep getting reassigned in the inner `describe` blocks anyway (i.e. `[mockedStore, dispatchedActions] = mockDrizzleStore()`). Might be a good idea to declare these in the inner `describe` instead.

2019-01-15 16:14 UTC, adrianmcli commented on test/contracts/create.test.js
> +    const aContract = await runSaga(mockedStore, instantiateWeb3Contract, options).done
Naming issue: How come this is named `aContract` instead of just `contract` or `contractInstance`?

2019-01-15 16:14 UTC, adrianmcli commented on test/blocks.test.js
> +beforeAll(() => {
This `beforeAll` block is hanging outside of any `describe` block. I don't think having nested `describe` blocks is a good idea though, I think I would favour repetition in this case.

2019-01-15 16:14 UTC, adrianmcli commented on test/accounts.test.js
> +beforeAll(() => {
This test file should probably be wrapped in a `describe` block.

2019-01-15 16:14 UTC, adrianmcli commented on test/accountBalances.test.js
> +beforeAll(() => {
This test file should probably be wrapped in a `describe` block.

2019-01-15 17:46 UTC, cds-amal commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Formatting issues will be resolved by `npm run format`

2019-01-15 17:50 UTC, cds-amal commented on CONTRIBUTING.md
> +No tests found related to files changed since last commit.
Makes sense

2019-01-15 17:52 UTC, cds-amal commented on src/web3/web3Saga.js
> +export function* getNetworkId({ web3 }) {
Thanks! We should move to the `husky` workflow eventually.

2019-01-15 17:58 UTC, cds-amal commented on test/accountBalances.test.js
> +  expect(dispatchedActions[0].accountBalance).toEqual(expectedBalance)
Not for this time @honestbonsai. This PR is large and I want to incorporate it before adding more.

2019-01-15 18:17 UTC, cds-amal commented on test/web3.test.js
> +    let mEnable
I removed the references due to a Jest issue I'm investigating (see blow) and left it in as I'm actively pursuing a workaround. I also did not want to add more weight to this PR and decided the test functions for evaluating the code-path of the Subject.

The issue is where a jest mock is invoked in a generator and the invocation is not recorded which causes subsequent expectations to fail, like:  `mEnable.toHaveBeenCalledTimes(1)` to fail.

2019-01-15 18:24 UTC, adrianmcli commented on test/web3.test.js
> +    let mEnable
Ah okay, understandable; thanks for explaining.

Just a naming nitpick, but maybe `mockEnable` would be a bit more explicit as to what the variable does? The one-letter prefix pattern is not so common in JS when compared to some other languages.

2019-01-15 20:42 UTC, cds-amal commented on test/web3.test.js
> +    let mEnable
A reasonable nit. I'll update that.

2019-01-15 21:45 UTC, honestbonsai commented on test/accountBalances.test.js
> +  expect(dispatchedActions[0].accountBalance).toEqual(expectedBalance)
Cool we can open up new PRs for that in the future then

2019-01-15 23:40 UTC, cds-amal commented on test/utils/helpers.js
> +const mockWeb3 = () => new Web3(global.provider)
Good catch! Those are the real McCoys!

2019-01-15 23:54 UTC, cds-amal commented on test/blocks.test.js
> +beforeAll(() => {
`beforeAll` is a life-cycle testing method to execute before any tests in the current module. In this case I think it's a valid use case. This file has sibling describes, I'm not sure what should be repeated.

2019-01-16 00:08 UTC, adrianmcli commented on test/blocks.test.js
> +beforeAll(() => {
Actually nesting `describe` isn't so bad. Maybe something like this:

```js
import { createBlockChannel } from "../src/blocks/blocksSaga";
import { mockDrizzleStore, mockWeb3 } from "./utils/helpers";

describe("reading data from blocks", () => {
  let mockedStore;
  let web3;
  let syncAlways;

  beforeAll(() => {
    [mockedStore] = mockDrizzleStore();
    web3 = mockWeb3();
    syncAlways = false;
  });

  describe("by listening through websockets", () => {
    let blockListener;
    beforeEach(() => {
      blockListener = createBlockChannel({ mockedStore, web3, syncAlways });
    });

    test("listens for block headers", async () => {
      const blockListener = createBlockChannel({
        mockedStore,
        web3,
        syncAlways,
      });
      await web3.eth.sendTransaction({
        from: global.accounts[0],
        to: global.accounts[1],
        value: 200,
      });

      blockListener.take(event => {
        expect(event.type).toEqual("BLOCK_RECEIVED");
      });
    });

    test("unsubscribes from block headers", () => {
      blockListener.take(event => {
        expect(event.type).toEqual("@@redux-saga/CHANNEL_END");
      });

      blockListener.close();
    });
  });

  describe("by polling", () => {
    let blockPoller;
    beforeEach(() => {
      blockPoller = createBlockChannel({ mockedStore, web3, syncAlways });
    });

    test("polls for block headers", async () => {
      await web3.eth.sendTransaction({
        from: global.accounts[0],
        to: global.accounts[1],
        value: 200,
      });

      blockPoller.take(event => {
        expect(event.type).toEqual("BLOCK_FOUND");
      });
    });

    test("terminates from block polling", () => {
      blockPoller.take(event => {
        expect(event.type).toEqual("@@redux-saga/CHANNEL_END");
      });

      blockPoller.close();
    });
  });
});
```

Actually I might even be inclined to think that  `createBlockChannel()` doesn't need to live inside a `beforeEach` block, you can just repeat it for each test (there's only 4 anyway).

2019-01-16 01:58 UTC, cds-amal commented on .gitignore
> +package-lock.json
When I started working on this branch with @DiscRiskandBisque we needed to sync our work and package-lock caused merging difficulties. We placed it on ignore to make progress and I forgot to replace it before the PR

2019-01-16 02:00 UTC, cds-amal commented on src/web3/web3Saga.js
> -  yield takeEvery('SEND_WEB3_TX', callSendTx)
@honestbonsai The `SEND_WEB3_TX` action led to a code path that wasn't being utilized. I removed it because it touched the tests for web3Saga.

2019-01-16 02:11 UTC, cds-amal commented on test/blocks.test.js
> +beforeAll(() => {
@DiscRiskandBisque what are your thoughts? Both options look ok to me.

2019-01-16 02:23 UTC, adrianmcli commented on test/blocks.test.js
> +beforeAll(() => {
The problem with the original approach is that some variables were declared well in-advance of when they are used. In contrast, in the revised approach, it is made clear that `blockPoller` is only used within the scope of the 2 tests following its declaration.

2019-01-16 02:42 UTC, cds-amal commented on .eslintrc
> +  "extends": ["standard", "plugin:jest/recommended"],
I'm leaving "jest/prefer-to-have-length" which gives a better failure report when using (toHaveLength). It reports on
  `expect(dispatchedActions[0]['accounts']).toHaveLength(global.accounts.length)`
to encourage:
  `expect(dispatchedActions[0]['accounts'].length).toBe(global.accounts.length)`

2019-01-16 20:59 UTC, cds-amal commented on .babelrc
> +    "babel-plugin-syntax-async-functions"
It crept in during development. Removing!

2019-01-17 14:28 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
seems to be still a few more of these

2019-01-17 23:25 UTC, cds-amal commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
(edit: s/comma/semicolon.) @adrianmcli @honestbonsai I was wrong about `npm run format` fixing this issue. These **semicolons** are necessary to preserve the intent of the code. I suspect this might be the way prettier works to insert/delete tokens such that the result reduces to the same statement production. (I haven't stepped into that rabbit hole). A demonstration of the problem (without the **semicolons**) is:
```
global.window = {}
[mockedStore, dispatchedActions] = mockDrizzleStore()
```
going through prettier-stand would result in 

```
global.window = {}[(mockedStore, dispatchedActions)] = mockDrizzleStore()
```

2019-01-18 05:08 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
Prettier can do it, we just have a messed up eslint/standard/prettier config right now. I've confirmed it via the following [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAYgQwJYA2ArgE5wZg4DOcAOlAEZwBmEZAggQQBTUCeUMBm4BKDAF4AfBmD1aMSFCowMrCBJkBfOTADaDHCQA0GAwC8AuhuZRR9TSLlR0GAJoQiGKHDgATDDDqOL7+OBg0ALZ4ALSQBNAB6nhQvniU8BjJ8LD0TKwcXLxUAkKiEtKyUPKKyqoQ6uJaANw6+oYm5laNNnZQDk4uACoAFnhUGDgEVOoA7mwA1uN4zF4QMKNQAOaZ43ls5HgwuSz7nDz8gsJiUjKtBsamOJbWto59byBGIBAADjB40CoyFAhhIEBmAAVDAggSgcAA3CB4XyfEAMEg4MDzOAwADKP0xyU2yBgJCIcC+wxgEQIAHVRvAqASwHBcTDDnh4Yc+MhwFQgV9kjQSDAIRjNhEcMhmJMaF8AFZUAAeACEMVicbicBE4AAZZJwaWyikgRVK3FEghwACKRDWhqQMqmJoJJGFvIMDD48SgqJ+JCytOR62QAA4AAxff0QGi0jE-Xn+uDC+GGr5kACORDwZDFOAlUsdxq+kTwJLJJqolptdvgRudXxgOAYQd8IaQACZGxjCESAMIQCKS3lQaBpkBEGiDZuwp00TSaIA).

2019-01-18 12:24 UTC, cds-amal commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
The example options require semi-colons. If we adopt those changes every JS file will change. I don't think we should make that stylistic change for this already heavy PR

2019-01-18 12:41 UTC, adrianmcli commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
I'm not saying we do that in this PR, just manually correct it for this PR and I'll do a proper reformatting afterwards.

2019-01-18 13:43 UTC, cds-amal commented on test/web3.test.js
> +      ;[mockedStore, dispatchedActions] = mockDrizzleStore()
If we want to change the rules, I propose we proceed in a way that honors the `npm run format` step in this process. We can modify the rules to enforce semi-colon per statement in a subsequent PR.

2019-01-18 13:49 UTC, adrianmcli commented on .babelrc
> +    "babel-plugin-syntax-async-functions"
> Jest needs the babel transformation for its tests

Are you sure about this? What Node version are you on?

2019-01-18 18:49 UTC, cds-amal commented on .babelrc
> +    "babel-plugin-syntax-async-functions"
Drizzle uses babel and I want to be sure the tests files utilize the same transform rules. Jest by default will look for a babel configuration file, but since we encapsulate it in our webpack setup, Jest still needs to be informed. I'm using the `transform` config option to resolve to webpack's definition

https://jestjs.io/docs/en/getting-started.html#using-babel.

2019-01-18 19:17 UTC, adrianmcli commented
merge it!

2019-01-22 19:54 UTC, merged