Feature/improve redux state creation
ConsenSys-archive/drizzle-legacy pull request #205
Opened 2019-04-02 22:21 UTC by cds-amal

This PR allows Dapp developers to configure drizzle with their own middleware, sagas and reducers.

2019-04-03 08:25 UTC, adrianmcli requested changes
A couple changes here. Do try to proof-read a bit more before asking for a review next time. Otherwise, good work.

2019-04-03 08:25 UTC, adrianmcli commented on README.md
> +   **Note**: The above assumes you have no existing redux store and generates a new one. In the case you need something a little more sophisticaaated, consult our documentation for [using an Existing
- [ ] typo: "sophisticaaated"
- [ ] style (be concise): "If you need something more sophisticated..."
- [ ] style (be concise/capitalization consistency): "consult Using an Existing Redux Store or Delegating Redux Concerns to Drizzle"

2019-04-03 08:25 UTC, adrianmcli commented on src/contractStateUtils.js
> +export const generateContractInitialState = contractConfig =>
Consider refactoring with more intermediate variables and a step-by-step approach for readability/maintainability:

```js
export const generateContractInitialState = contractConfig => {
  const isConstant = x => x.type === "function" && x.constant === true;
  const constants = getAbi(contractConfig).filter(isConstant);
  const objectOfConstants = constants.reduce(
    (acc, x) => ({ ...acc, [x.name]: {} }),
    {}
  );
  return {
    initialized: false,
    synced: false,
    ...objectOfConstants
  };
};
```

2019-04-03 20:00 UTC, cds-amal commented on src/contractStateUtils.js
> +export const generateContractInitialState = contractConfig =>
definitely more readable. thanks!

2019-04-03 20:00 UTC, cds-amal commented on README.md
> +   **Note**: The above assumes you have no existing redux store and generates a new one. In the case you need something a little more sophisticaaated, consult our documentation for [using an Existing
updated, thanks. I'll be more careful with text.

2019-04-04 16:30 UTC, adrianmcli commented
lgtm

2019-04-04 16:31 UTC, merged