Refactor/use mw for drizzle instance
ConsenSys-archive/drizzle-legacy pull request #208
Opened 2019-04-04 13:03 UTC by cds-amal

This PR fixes the issue of not being able to update web3 contracts' from address when a new selected account is detected. It also unifies state mutation concerns - Drizzle class not mutates its own state, which was previously done in a saga/generator function. 

### Background
Drizzle currently splits state concerns in two locations 1) Redux store, to handle POJO state, and 2) the Drizzle Class instance for syncing Web3 Contract instance details. 

This is necessary because web3 Contracts are non-serializable, as the trade offs are not worth it. See [this Redux FAQ](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)

### Problem

Web3 Contracts have a mutable sendAccount property that web3 uses to sign send transactions. This value should reflect the current account designated by the wallet provider and it currently is not synchronized by drizzle.

The architecture makes it difficult to sync drizzle's contract list (maintained in the Drizzle class) with redux actions originating from web3 which, rightly, have no reference to drizzle's instance.

2019-04-18 04:23 UTC, adrianmcli requested changes
If it passes manual testing, then this should be good to merge. There are no glaring issues, just a Prettier reformat is needed.

To be honest, it's such a big refactor that it's really hard for me to tell if it'll work the same as before by just looking at the code. Consider using stacked-PRs (like stacked-diffs) next time.

For example:

1. Create a branch `fix/the-thing` and push it to the repo.
2. Make another branch called `fix/the-thing/replace-x` and do your (small amount of) work there.
3. When done, make a PR to merge `fix/the-thing/replace-x` into `fix/the-thing`.
4. For the next part of work, make a new branch `fix/the-thing/replace-y`.
5. Submit a PR to merge `fix/the-thing/replace-y` into `fix/the-thing`.
6. Once everything is merged into `fix/the-thing`, make a PR to merge that into `master` (or `develop`, whichever is the repo's default branch).

This is basically emulating stacked-diffs, but this is the best we can do w/ Github. There's some blog article describing this, I'll have to find it later.

2019-04-18 04:23 UTC, adrianmcli commented on src/Drizzle.js
> +  return web3Contract || new web3.eth.Contract(abi, networks[networkId].address, { from: selectedAccount, data: deployedBytecode })
Perhaps Prettier was not run? This line is very long.

2019-04-18 06:22 UTC, cds-amal commented on src/Drizzle.js
> +  return web3Contract || new web3.eth.Contract(abi, networks[networkId].address, { from: selectedAccount, data: deployedBytecode })
Good points on the stacked git workflow @adrianmcli. 

TBH, I was expecting more discussion on this PR and worry its size may have prevented that. I'll close this PR and use the suggested git flow because I want to prioritize feedback opportunities.

2019-04-18 07:09 UTC, adrianmcli commented on src/Drizzle.js
> +  return web3Contract || new web3.eth.Contract(abi, networks[networkId].address, { from: selectedAccount, data: deployedBytecode })
Sounds good, thx.

2019-05-23 17:31 UTC, davidmurdoch approved these changes
LGTM! Just commented on a few lines with some questions for you to ponder.

2019-05-23 17:31 UTC, davidmurdoch commented on src/drizzle-middleware.js
> +    const newAccount = action.accounts[0]
If, by chance, `action.accounts` is an empty array this will result in an `undefined`. Not sure if this is possible with any provider, so it might not even matter.

2019-05-23 17:31 UTC, davidmurdoch commented on src/drizzle-middleware.js
> +      console.error('Attempt to add a duplicate contract.\n', error)
It _could_ be possible for the error here to be unrelated to a duplicate contract, so this logged error _could_ be incorrect.

2019-05-23 17:31 UTC, davidmurdoch commented on src/drizzle-middleware.js
> +  if (type === 'ADD_CONTRACT' && drizzleInstance) {
If an `ADD_CONTRACT` event was emitted and there is no `drizzleInstance`, is this an exceptional circumstance that should be dispatched as such?

2019-06-05 20:30 UTC, cds-amal commented on src/drizzle-middleware.js
> +    const newAccount = action.accounts[0]
Good point - will keep a note of this for when the provider field expands.

2019-06-05 20:33 UTC, cds-amal commented on src/drizzle-middleware.js
> +  if (type === 'ADD_CONTRACT' && drizzleInstance) {
drizzleInstance comes before any contracts are added. It's an edge case I don't see how we can get to.

2019-06-07 08:09 UTC, adrianmcli commented on src/Drizzle.js
> +  const networkId = state.web3.networkId
I'm a little worried about not having the web3 object here. Maybe something like this would be better?

```js
const networkId = state.web3 && state.web3.networkId
```

2019-06-07 08:09 UTC, adrianmcli commented on src/Drizzle.js
> +  )
It might be better to do an early return with this function earlier so you don't go through the work of getting all these variables when you already have a `web3Contract`.

So maybe something like:

```js
export const getOrCreateWeb3Contract = (store, contractConfig = {}, web3) => {
  if (contractConfig.web3Contract) {
    return web3Contract
  }

  const state = store.getState()
  const networkId = state.web3.networkId
  const selectedAccount = state.accounts[0]
  // etc...

  return new web3.eth.Contract(abi, address, { from, data })
}
```

2019-06-07 08:09 UTC, adrianmcli commented on src/Drizzle.js
> +    if (!this.contracts[contractName]) {
Might be a good idea to leave a comment specifying that you are removing the contract from:

1. `this.contractList`
2. `this.contracts`
3. `this.loadingContract`

Like:

```js
// this removes the contract from `this.contractList`, `this.contracts`, and `this.loadingContract`
```

Otherwise, I was initially confused as to why there are so many lines when I just want to remove 1 contract.

2019-06-07 08:09 UTC, adrianmcli commented on src/drizzle-middleware.js
> +      drizzleInstance.contractList.forEach(contract => {
Leave a short comment here mentioning that you are replacing the `from` field in each contract w/ the new account.

```js
// replace `from` field w/ new account
```

2019-06-07 08:09 UTC, adrianmcli commented on test/drizzle/api.test.js
> +      // 1 in cstor, 2 in addContract
Maybe I'm not familiar with the abbreviation, but what is `cstor`?

2019-06-09 13:16 UTC, adrianmcli commented
@cds-amal LGTM, go ahead and merge!

2019-06-10 18:42 UTC, merged

2019-06-16 10:00 UTC, sushmitsarmah commented
This issue is closed but whats the solution? I am still getting this error.

2019-06-16 16:59 UTC, adrianmcli commented
@sushmitsarmah I don't think we have made a release yet. @cds-amal let's put that on the table this week.

2019-06-26 02:08 UTC, atlanticstarr1 commented
Hi all, when is the next release expected ?