Fix/coinbase init web3
ConsenSys-archive/drizzle-legacy pull request #224
Opened 2019-05-15 03:56 UTC by cds-amal

This PR addresses #220 

It also sets web3.status to WEB3_USER_DENIED when user denies dap access to accounts. this allows the UI to act accordingly.

2019-06-10 01:43 UTC, adrianmcli requested changes

2019-06-10 01:43 UTC, adrianmcli commented on src/drizzleStatus/drizzleStatusSaga.js
> +    //
There's an extra comment line here and a grammar mistake. It could also be a bit more specific.

Like:

```js
// Client may opt out of connecting their accounts to the dapp
```

2019-06-10 01:43 UTC, adrianmcli commented on src/drizzleStatus/drizzleStatusSaga.js
> +      if (web3.currentProvider.isMetaMask && !window.ethereum) {
Do note that evaluating `window.ethereum` directly will cause it to fail in server-side environments. But maybe it's fine since the `isMetaMask` wouldn't be satisfied outside of the browser anyway. Thought I'd leave this comment anyway.

2019-06-10 01:43 UTC, adrianmcli commented on src/drizzleStatus/drizzleStatusSaga.js
> +      // Get initial accounts list and balances.
This goes for the rest of this PR as well. And it might just be a nit pick, but we tend not to use periods to end comments unless there is more than one sentence (like in multi-line comments). But I think the code is already a mix anyway, so do as you wish. Just wanted to bring up the consistency issue.

2019-06-10 01:43 UTC, adrianmcli commented on src/web3/web3Saga.js
> +        console.log('selectedAccount', selectedAccount)
Does Drizzle have other `console.log` statements within it? Dapp builders may not like this.

2019-06-10 01:43 UTC, adrianmcli commented on test/web3.test.js
> +      global.window = { ethereum }
This can be re-written like this:

```js
const ethereum = { enable: jest.fn() }
global.window = { ethereum }
```

2019-06-10 01:43 UTC, adrianmcli commented on test/web3.test.js
> +    let ethereum
Does `ethereum`  and `mockedEthereumEnable` need to be shared variables? See below for more info.

2019-06-10 01:43 UTC, adrianmcli commented on test/web3.test.js
> +      global.window = { ethereum }
Since it doesn't look like any of the intermediate variables are used later on, the above 3 lines can be re-written as:

```js
global.window = {
  ethereum: { enable: jest.fn(() => '0x123') }
}
```

2019-06-10 01:43 UTC, adrianmcli commented on test/web3.test.js
> +      global.window = { ethereum }
Same rationale as above:

```js
global.window = {
  ethereum: { enable: jest.fn(() => undefined) }
}
```

2019-06-10 01:43 UTC, adrianmcli commented on test/web3.test.js
> +      global.window = { ethereum }
Similar rationale as above:

```js
global.window = {
  ethereum: {
    enable: jest.fn(() => throw new Error('oops'))
  }
}
```

2019-06-10 16:39 UTC, cds-amal commented on src/drizzleStatus/drizzleStatusSaga.js
> +      // Get initial accounts list and balances.
Lets address in a `good-first-issue` ask.

2019-06-10 16:41 UTC, cds-amal commented on src/web3/web3Saga.js
> +        console.log('selectedAccount', selectedAccount)
That should not be there. Thanks.

2019-06-10 16:49 UTC, cds-amal commented on test/web3.test.js
> +    let ethereum
I'm trying to follow a naming style to make it easier to reason about the tests. It's a cue to remind myself to check results of `mockedXXX` in a test when I switch context over time.

2019-06-10 16:52 UTC, cds-amal commented on test/web3.test.js
> +      global.window = { ethereum }
See above justification

2019-06-10 16:52 UTC, cds-amal commented on test/web3.test.js
> +      global.window = { ethereum }
See above justification

2019-06-10 17:10 UTC, adrianmcli commented on test/web3.test.js
> +    let ethereum
I agree with the naming, but it doesn't need to be a shared variable between the tests. It's a bit easier to reason about if it's just defined (and used) in each test locally.

2019-06-10 17:23 UTC, adrianmcli commented on test/web3.test.js
> +    let ethereum
@cds-amal forgot to tag yo here. Please see above response.

2019-06-10 17:39 UTC, cds-amal commented on test/web3.test.js
> +    let ethereum
Oh, I misunderstood your comment. Thought you meant enable and mockedEnable resolving to the same "shared" object. Scoping? No strong opinions. updated.

2019-06-10 17:40 UTC, cds-amal commented on test/web3.test.js
> +    let ethereum
@adrianmcli ☝️ . Let me know

2019-06-10 18:22 UTC, adrianmcli commented on test/web3.test.js
> +    let ethereum
Great, looks good.

2019-07-18 15:23 UTC, cds-amal commented on test/web3.test.js
> +      global.window = { ethereum }
Thanks @adrianmcli

2019-07-18 16:33 UTC, adrianmcli approved these changes

2019-07-18 21:27 UTC, merged